/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fridge.tertainment;

import java.sql.*;
import fridge.tertainment.DataBase.*;

//import fridge.tertainment.GUI.GUI_Main;
import fridge.tertainment.sqlConnector.Repository;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    static void Test() {
        try {
            Repository repository = new Repository();
            var list = repository.recipes.GetRecipeDTOs();
            for (var item : list) System.out.println(item.toString());
            repository.recipes.UpdateRecipe(list.get(0));
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());

        Test();

        //new GUI_Main();Chang
    }
}
