/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fridge.tertainment;

import fridge.tertainment.GUI.GUI_Main;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        new GUI_Main();
        
    }
}
