/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fridge.tertainment;

import java.util.ArrayList;

import fridge.tertainment.DataBase.DTO.IngredienceDTO;
import fridge.tertainment.DataBase.DTO.RecipeDTO;

//import fridge.tertainment.GUI.GUI_Main;
import fridge.tertainment.sqlConnector.Repository;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    static void Test() {
        try {
            Repository repository = new Repository();
            repository.ingrediences.Create(new IngredienceDTO("Salt"));
            repository.recipes.Create(new RecipeDTO("Opskrift", "Lav Mad", 2, 2000, 60));
            ArrayList<RecipeDTO> list = repository.recipes.GetAll();
            for (RecipeDTO item : list) System.out.println(item.toString());
            repository.recipes.Update(list.get(0));
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());

        Test();

        //new GUI_Main();Chang
    }
}
